# Generated by Django 2.2 on 2020-05-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('registration', models.CharField(max_length=10, unique=True)),
                ('NID', models.IntegerField(unique=True)),
                ('Cancer_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('Visit', models.IntegerField()),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('Contact', models.IntegerField()),
                ('Emergency', models.IntegerField(blank=True)),
                ('Age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Third', 'Third')], max_length=20)),
                ('maritial_status', models.CharField(choices=[('Married', 'Married'), ('Unmarrried', 'Unmarried')], max_length=20)),
                ('occupation', models.TextField()),
                ('blood_groups', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O-'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('Weight', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('BMI', models.IntegerField(blank=True)),
                ('Concomitant', models.TextField(blank=True)),
                ('BSA', models.IntegerField(blank=True)),
                ('blood_pressure', models.IntegerField(blank=True)),
                ('temperature', models.IntegerField(blank=True)),
            ],
        ),
    ]
