# Generated by Django 2.2 on 2020-05-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='BMI',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='BSA',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Concomitant',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_groups',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='temperature',
        ),
    ]
