# Generated by Django 2.2 on 2020-05-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0002_auto_20200514_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='BMI',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='BSA',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Concomitant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_groups',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O-'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
