# Generated by Django 2.2 on 2020-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0004_auto_20200514_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BMI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='BSA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Concomitant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
