# Generated by Django 2.2 on 2020-05-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0011_auto_20200516_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField()),
                ('noticefiles', models.FileField(upload_to='noticefilesdoc/')),
            ],
        ),
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardnum', models.IntegerField()),
                ('bednum', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('admissiondate', models.DateField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'Other')], max_length=100)),
                ('information', models.TextField()),
                ('reports', models.FileField(blank=True, null=True, upload_to='wardreportsdoc/')),
            ],
        ),
    ]
