# Generated by Django 2.2 on 2020-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0012_notice_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ECHO_CARDIOgraphy',
            new_name='echo_cardiography',
        ),
        migrations.AddField(
            model_name='patient',
            name='additionalfiles',
            field=models.FileField(blank=True, null=True, upload_to='patientadditionalfilesdoc/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='historyfiles',
            field=models.FileField(blank=True, null=True, upload_to='patienthistorydoc/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='investigationfiles',
            field=models.FileField(blank=True, null=True, upload_to='investigationfilesdoc/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='physicalexamfiles',
            field=models.FileField(blank=True, null=True, upload_to='patientphysicalexamdoc/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='reportsfiles',
            field=models.FileField(blank=True, null=True, upload_to='patientreportsdoc/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticefiles',
            field=models.FileField(blank=True, null=True, upload_to='noticefilesdoc/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='maritial_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarrried', 'Unmarried')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, null=True, upload_to='patientimages/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'Other')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staffimage/'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
