# Generated by Django 2.2 on 2020-05-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0013_auto_20200517_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='admissiondate',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='information',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='reports',
        ),
        migrations.AddField(
            model_name='ward',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='patientid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
