# Generated by Django 2.2 on 2020-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0014_auto_20200520_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oncallsaturday', models.CharField(blank=True, max_length=200, null=True)),
                ('oncallsunday', models.CharField(blank=True, max_length=200, null=True)),
                ('oncallmonday', models.CharField(blank=True, max_length=200, null=True)),
                ('oncalltuesday', models.CharField(blank=True, max_length=200, null=True)),
                ('oncallwednesday', models.CharField(blank=True, max_length=200, null=True)),
                ('oncallthursday', models.CharField(blank=True, max_length=200, null=True)),
                ('roundsaturday', models.CharField(blank=True, max_length=200, null=True)),
                ('roundsunday', models.CharField(blank=True, max_length=200, null=True)),
                ('roundmonday', models.CharField(blank=True, max_length=200, null=True)),
                ('roundtuesday', models.CharField(blank=True, max_length=200, null=True)),
                ('roundwednesday', models.CharField(blank=True, max_length=200, null=True)),
                ('roundthursday', models.CharField(blank=True, max_length=200, null=True)),
                ('planningsaturday', models.CharField(blank=True, max_length=200, null=True)),
                ('planningsunday', models.CharField(blank=True, max_length=200, null=True)),
                ('planningmonday', models.CharField(blank=True, max_length=200, null=True)),
                ('planningtuesday', models.CharField(blank=True, max_length=200, null=True)),
                ('planningwednesday', models.CharField(blank=True, max_length=200, null=True)),
                ('planningthursday', models.CharField(blank=True, max_length=200, null=True)),
                ('outdoorsaturday', models.CharField(blank=True, max_length=200, null=True)),
                ('outdoorsunday', models.CharField(blank=True, max_length=200, null=True)),
                ('outdoormonday', models.CharField(blank=True, max_length=200, null=True)),
                ('outdoortuesday', models.CharField(blank=True, max_length=200, null=True)),
                ('outdoorwednesday', models.CharField(blank=True, max_length=200, null=True)),
                ('outdoorthursday', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
